version: '3.5'

services:
  jibri:
    image: jitsi/jibri:${JITSI_IMAGE_VERSION:-unstable}
    restart: ${RESTART_POLICY:-unless-stopped}

    privileged: true
    shm_size: '2gb'

    devices:
      - /dev/snd:/dev/snd

    volumes:
      - ${CONFIG}/jibri:/config
      - ./jibri/finalize.sh:/config/finalize.sh
      - /dev/shm:/dev/shm
      - /tmp:/tmp

      # 🔥 ADD THESE
      - /usr/bin/aws:/usr/bin/aws
      - /root/.aws:/root/.aws

    environment:
      - DISPLAY=:0
      - CHROMIUM_FLAGS=--no-sandbox --disable-dev-shm-usage

      - JIBRI_FINALIZE_RECORDING_SCRIPT_PATH=/config/finalize.sh

      - JIBRI_XMPP_USER
      - JIBRI_XMPP_PASSWORD
      - JIBRI_RECORDER_USER
      - JIBRI_RECORDER_PASSWORD
      - JIBRI_RECORDING_DIR
      - JIBRI_RECORDING_RESOLUTION

      - JIBRI_BREWERY_MUC
      - XMPP_AUTH_DOMAIN
      - XMPP_DOMAIN
      - XMPP_INTERNAL_MUC_DOMAIN
      - XMPP_MUC_DOMAIN
      - XMPP_HIDDEN_DOMAIN
      - XMPP_SERVER

      - PUBLIC_URL
      - TZ

    depends_on:
      - jicofo

    networks:
      meet.jitsi:
